/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachine.gui;

/**
 *
 * @author Temiboi
 */
public class AdminGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminGUI.class.getName());

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdminScreen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChangePassword = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSlot = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtValue = new javax.swing.JTextArea();
        btnCollectRevenue = new javax.swing.JButton();
        btnViewRevenue = new javax.swing.JButton();
        btnCheckLowStock = new javax.swing.JButton();
        btnRestock = new javax.swing.JButton();
        btnReprice = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        ComboType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAdminScreen.setColumns(20);
        txtAdminScreen.setRows(5);
        jScrollPane1.setViewportView(txtAdminScreen);

        txtChangePassword.setColumns(20);
        txtChangePassword.setRows(5);
        txtChangePassword.setBorder(javax.swing.BorderFactory.createTitledBorder("New Password"));
        jScrollPane2.setViewportView(txtChangePassword);

        txtSlot.setColumns(20);
        txtSlot.setRows(5);
        txtSlot.setBorder(javax.swing.BorderFactory.createTitledBorder("Slot ID"));
        jScrollPane3.setViewportView(txtSlot);

        txtValue.setColumns(20);
        txtValue.setRows(5);
        txtValue.setBorder(javax.swing.BorderFactory.createTitledBorder("New Price / Restock Amount"));
        jScrollPane4.setViewportView(txtValue);

        btnCollectRevenue.setText("Collect Revenue");
        btnCollectRevenue.addActionListener(this::btnCollectRevenueActionPerformed);

        btnViewRevenue.setText("View Revenue");
        btnViewRevenue.addActionListener(this::btnViewRevenueActionPerformed);

        btnCheckLowStock.setText("Check Low Stock");
        btnCheckLowStock.addActionListener(this::btnCheckLowStockActionPerformed);

        btnRestock.setText("Restock");
        btnRestock.addActionListener(this::btnRestockActionPerformed);

        btnReprice.setText("Reprice");
        btnReprice.addActionListener(this::btnRepriceActionPerformed);

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(this::btnChangePasswordActionPerformed);

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        ComboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FruitProduct", "PetFood", "PetToy", "AirPods", "Charger", "Powerbank", "CarbonatedCola", "SodaWater", "NonCarbonatedJuice", "StillWater", "TeaBlack", "BiscuitPacket", "ChocolateBar", "Chips", "Sandwich", "Coffee" }));
        ComboType.addActionListener(this::ComboTypeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckLowStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestock))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnReprice)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnLogOut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnViewRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCollectRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnViewRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnLogOut))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCollectRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCheckLowStock)
                                    .addComponent(btnRestock)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnChangePassword))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddProduct)
                                    .addComponent(btnReprice)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollectRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectRevenueActionPerformed
        vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
        double collected = adminLogic.collectRevenue();
        txtAdminScreen.append("Successfully collected $" + String.format("%.2f", collected) + "! The vault is now empty.\n");
    }//GEN-LAST:event_btnCollectRevenueActionPerformed

    private void btnViewRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRevenueActionPerformed
        vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
        double total = adminLogic.getTotalRevenue();
        txtAdminScreen.append("Current Revenue: $" + String.format("%.2f", total) + "\n");
    }//GEN-LAST:event_btnViewRevenueActionPerformed

    private void btnCheckLowStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckLowStockActionPerformed
        vendingmachine.VendingMachine machine = vendingmachine.VendingMachine.getInstance();
        java.util.List<vendingmachine.products.AbstractProduct> lowStock = machine.getLowStockProducts();
        
        if (lowStock.isEmpty()) {
            txtAdminScreen.append("All products are perfectly stocked!\n");
        } else {
            txtAdminScreen.append("WARNING - Low stock items:\n");
            for (vendingmachine.products.AbstractProduct p : lowStock) {
                txtAdminScreen.append("Slot " + p.getSlotId() + ": " + p.getName() + " (Only " + p.getStockQuantity() + " left)\n");
            }
        }
        
    }//GEN-LAST:event_btnCheckLowStockActionPerformed

    private void btnRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestockActionPerformed
        try {
            String slot = txtSlot.getText().trim().toUpperCase();
            if (!slot.matches("[A-D][0-9]")) {
                txtAdminScreen.append("[X] Error: Slot must be A-D followed by 0-9 (e.g., A1, C3).\n");
                return;
            }
            int amount = Integer.parseInt(txtValue.getText().trim());

            vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
            adminLogic.restock(slot, amount);

            txtAdminScreen.append("Restocked slot " + slot + " with " + amount + " items.\n");

            txtSlot.setText("");
            txtValue.setText("");
        } catch (NumberFormatException e) {
            txtAdminScreen.append("[X] Error: Please enter a valid number for the amount.\n");
        } catch (vendingmachine.ProductNotFoundException e) {
            txtAdminScreen.append("[X] Error: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_btnRestockActionPerformed

    private void btnRepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepriceActionPerformed
        try {
            String slot = txtSlot.getText().trim().toUpperCase();
            if (!slot.matches("[A-D][0-9]")) {
                txtAdminScreen.append("[X] Error: Slot must be A-D followed by 0-9 (e.g., A1, C3).\n");
                return;
            }
            double newPrice = Double.parseDouble(txtValue.getText().trim());
            
            vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
            adminLogic.reprice(slot, newPrice);
            
            txtAdminScreen.append("Repriced slot " + slot + " to $" + String.format("%.2f", newPrice) + "\n");
            
            txtSlot.setText("");
            txtValue.setText("");
            
        } catch (NumberFormatException e){
            txtAdminScreen.append("[X] Error: Please enter a valid decimal number for the price.\n");
        } catch (vendingmachine.ProductNotFoundException e){
            txtAdminScreen.append("[X] Error: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_btnRepriceActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        String newPassword = txtChangePassword.getText().trim();

        if (newPassword.isEmpty()) {
            txtAdminScreen.append("[X] Error: Password cannot be empty.\n");
            return; // Stops the code here so it doesn't save a blank password
        }

        vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
        adminLogic.changePassword(newPassword);

        txtAdminScreen.append("Success: Admin password updated! Don't forget it.\n");

        // Clear the box
        txtChangePassword.setText("");
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try{
            String type = ComboType.getSelectedItem().toString();
            String slot = txtSlot.getText().trim().toUpperCase();
            
            if (slot.isEmpty()) {
                txtAdminScreen.append("[X] Error: Slot ID cannot be empty.\n");
                return;
            }
            if (!slot.matches("[A-D][0-9]")) {
                txtAdminScreen.append("[X] Error: Slot must be A-D followed by 0-9 (e.g., A1, C3).\n");
                return;
            }
            double price = Double.parseDouble(txtValue.getText().trim());

            String stockStr = javax.swing.JOptionPane.showInputDialog(this, "Enter the starting stock quantity:");
            if (stockStr == null || stockStr.trim().isEmpty()) {
                    txtAdminScreen.append("[X] Cancelled adding new product.\n");
                    return; 
            }
            
            int stock = Integer.parseInt(stockStr.trim());
            
            vendingmachine.logic.LogicAdmin adminLogic = new vendingmachine.logic.LogicAdmin();
            
            try {
                vendingmachine.products.AbstractProduct createdProd = adminLogic.addNewProduct(slot, price, stock, type);
                txtAdminScreen.append("Success: Added " + stock + "x '" + createdProd.getName() + "' to slot " + slot + "!\n");
                
                txtSlot.setText("");
                txtValue.setText("");
                
            } catch (Exception ex){
                txtAdminScreen.append("[X] Critical Error Saving Product: " + ex.getMessage() + "\n");
            }
            
        }catch (NumberFormatException e) {
            txtAdminScreen.append("[X] Error: Please enter valid numbers for price and stock.\n");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to log out of the Admin Panel?", 
            "Confirm Log Out", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            vendingmachine.gui.TestGUI mainWindow = new vendingmachine.gui.TestGUI();
            mainWindow.setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboType;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCheckLowStock;
    private javax.swing.JButton btnCollectRevenue;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReprice;
    private javax.swing.JButton btnRestock;
    private javax.swing.JButton btnViewRevenue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtAdminScreen;
    private javax.swing.JTextArea txtChangePassword;
    private javax.swing.JTextArea txtSlot;
    private javax.swing.JTextArea txtValue;
    // End of variables declaration//GEN-END:variables
}
