/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachine.gui;

/**
 *
 * @author Temiboi
 */
public class TestGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestGUI.class.getName());

    /**
     * Creates new form TestGUI
     */
    public TestGUI() {
        
        initComponents();
        
        // --- BOOT-UP SEQUENCE ---
        txtScreen.setText("=== MULTI-PURPOSE VENDING MACHINE ===\n");
        txtScreen.append("Loading inventory...\n\n");
        
        // Grab the inventory map from your backend
        java.util.Map<String, vendingmachine.products.AbstractProduct> inventory = 
            vendingmachine.VendingMachine.getInstance().getInventory();
            
        // Loop through every item and print it to the screen
        for (java.util.Map.Entry<String, vendingmachine.products.AbstractProduct> entry : inventory.entrySet()) {
            vendingmachine.products.AbstractProduct p = entry.getValue();
            
            // Check if it's empty so we can put a nice tag on it
            String status = p.isAvailable() ? "[$" + String.format("%.2f", p.getPrice()) + "] - Qty: " + p.getStockQuantity() : "[EMPTY]";
            
            txtScreen.append("Slot " + entry.getKey() + " : " + p.getName() + " " + status + "\n");
        }
        
        txtScreen.append("-------------------------------------\n");
        txtScreen.append("Ready! Click the on-screen keypad to select a slot.\n");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtScreen = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtScreen.setColumns(20);
        txtScreen.setRows(5);
        txtScreen.setText("txtScreen\n\n\n");
        jScrollPane1.setViewportView(txtScreen);

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        jButton5.setText("A");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel2.add(jButton5);

        jButton6.setText("1");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel2.add(jButton6);

        jButton7.setText("2");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel2.add(jButton7);

        jButton13.setText("3");
        jButton13.addActionListener(this::jButton13ActionPerformed);
        jPanel2.add(jButton13);

        jButton14.setText("B");
        jButton14.addActionListener(this::jButton14ActionPerformed);
        jPanel2.add(jButton14);

        jButton16.setText("4");
        jButton16.addActionListener(this::jButton16ActionPerformed);
        jPanel2.add(jButton16);

        jButton15.setText("5");
        jButton15.addActionListener(this::jButton15ActionPerformed);
        jPanel2.add(jButton15);

        jButton12.setText("6");
        jButton12.addActionListener(this::jButton12ActionPerformed);
        jPanel2.add(jButton12);

        jButton9.setText("C");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel2.add(jButton9);

        jButton8.setText("7");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel2.add(jButton8);

        jButton11.setText("8");
        jButton11.addActionListener(this::jButton11ActionPerformed);
        jPanel2.add(jButton11);

        jButton10.setText("9");
        jButton10.addActionListener(this::jButton10ActionPerformed);
        jPanel2.add(jButton10);

        jButton3.setText("D");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3);

        jButton4.setText("*");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4);

        jButton18.setText("0");
        jButton18.addActionListener(this::jButton18ActionPerformed);
        jPanel2.add(jButton18);

        jButton17.setText("#");
        jButton17.addActionListener(this::jButton17ActionPerformed);
        jPanel2.add(jButton17);

        btnEnter.setText("Enter");
        btnEnter.addActionListener(this::btnEnterActionPerformed);

        jButton19.setText("Clear");
        jButton19.addActionListener(this::jButton19ActionPerformed);

        txtInput.setEditable(false);
        txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Slot ID"));
        txtInput.addActionListener(this::txtInputActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInput)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        txtInput.setText(txtInput.getText() + "B");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtInput.setText(txtInput.getText() + "C");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        txtInput.setText(txtInput.getText() + "0");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        txtInput.setText(txtInput.getText() + "A");
      }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtInput.setText(txtInput.getText() + "D");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtInput.setText(txtInput.getText() + "*");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        txtInput.setText(txtInput.getText() + "#");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtInput.setText(txtInput.getText() + "1");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        txtInput.setText(txtInput.getText() + "2");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        txtInput.setText(txtInput.getText() + "3");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        txtInput.setText(txtInput.getText() + "4");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        txtInput.setText(txtInput.getText() + "5");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        txtInput.setText(txtInput.getText() + "6");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        txtInput.setText(txtInput.getText() + "7");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        txtInput.setText(txtInput.getText() + "8");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        txtInput.setText(txtInput.getText() + "9");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        String input = txtInput.getText().trim();
        
        if (input.length() == 2){
            vendingmachine.logic.LogicUser logic = new vendingmachine.logic.LogicUser();

            if (logic.checkAvailability(input)) {
                double price = logic.getItemPrice(input);
                
                Object[] opts = {"Cash", "Credit Card", "Bank Card"};
                int choice = javax.swing.JOptionPane.showOptionDialog(this, 
                    "Item Price is $" + String.format("%.2f", price) + ".\nChoose payment method:",
                    "Payment Options", 
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.PLAIN_MESSAGE, 
                    null, opts, opts[0]);
                
                if (choice == -1) {
                    txtScreen.append("Purchase cancelled.\n");
                    txtInput.setText("");
                    return; 
                }
                
                vendingmachine.logic.ChangeCalculator.PaymentMethod method = 
                      choice == 1 ? vendingmachine.logic.ChangeCalculator.PaymentMethod.CREDIT_CARD
                    : choice == 2 ? vendingmachine.logic.ChangeCalculator.PaymentMethod.BANK_CARD
                    : vendingmachine.logic.ChangeCalculator.PaymentMethod.CASH;
                
                vendingmachine.logic.ChangeCalculator.PaymentResult payment = null;
                
                // 2. Handle CASH
                if (method == vendingmachine.logic.ChangeCalculator.PaymentMethod.CASH) {
                    String moneyInput = javax.swing.JOptionPane.showInputDialog(this, 
                        "Enter Cash Inserted (e.g., 5.00):");
                    
                    if (moneyInput != null && !moneyInput.trim().isEmpty()) {
                        try {
                            double moneyInserted = Double.parseDouble(moneyInput);
                            payment = vendingmachine.logic.ChangeCalculator.processPayment(price, moneyInserted, method);
                        } catch (NumberFormatException ex) {
                            txtScreen.append("[X] Error: Please enter a valid number for cash.\n");
                            txtInput.setText("");
                            return; // Stop the transaction
                        }
                    } else {
                        txtScreen.append("Purchase cancelled.\n");
                        txtInput.setText("");
                        return; // Stop the transaction
                    }
                }
                // 3. Handle Cards
                else {
                    payment = vendingmachine.logic.ChangeCalculator.processPayment(price, price, method);
                }
                    
                if (payment != null && payment.isSuccess()) {
                    boolean saleResult = logic.processSale(input);

                    if (saleResult) {
                        txtScreen.append("Sale Processed! " + payment.getMessage() + "\n");
                        if (payment.getChangeAmount() > 0) {
                            txtScreen.append("Dispensing Change:\n");
                            for (java.util.Map.Entry<String, Integer> entry : payment.getChangeBreakdown().entrySet()) {
                                txtScreen.append("  -> " + entry.getValue() + "x " + entry.getKey() + "\n");
                                }
                        }
                        txtScreen.append("----------------------------\n");
                    } else {
                        txtScreen.append("Error: Sale failed during dispensing.\n");
                    }
                } else if (payment != null) {
                    // If they didn't put enough money in, or card declined
                    txtScreen.append("[X] Payment Error: " + payment.getMessage() + "\n");
                }
                
            } else {
                txtScreen.append("Sorry, slot " + input + " is empty or out of stock!\n");
            }
        //This *#AB1C3 here is a dev convenience only.     
        } else if (input.equals("*#AB1C3")) {
            String password = javax.swing.JOptionPane.showInputDialog(this, "Enter Admin Password:");
            
            if (password != null) {
                vendingmachine.data.FileManager fm = new vendingmachine.data.FileManager();

                if (fm.checkAdminPassword(password)) {
                    txtScreen.append("Admin Login Successful! Opening Admin Panel...\n");
                    vendingmachine.gui.AdminGUI adminWindow = new vendingmachine.gui.AdminGUI();
                    
                    adminWindow.setVisible(true);
                    this.dispose();
                    
                } else {
                    txtScreen.append("Error: Incorrect Admin Password.\n");
                }
            }
        } else {
            txtScreen.append("Error: Invalid input! Please enter a valid slot (e.g., A1).\n");
        }
        txtInput.setText("");
    }//GEN-LAST:event_btnEnterActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        txtInput.setText("");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Safe Exit
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to exit the application?", 
            "Confirm Shutdown", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); //0 for safe exit.
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextArea txtScreen;
    // End of variables declaration//GEN-END:variables
}
